---
- name: Enable Google Chrome Repository
  template:
    src: "../templates/google-chrome.repo.j2"
    dest: /etc/yum.repos.d/google-chrome.repo
  tags: packages

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - libvirt-client
    - libguestfs-tools
    - virt-manager
    - virt-install
    - scap-security-guide
    - openscap
    - scap-workbench
    - google-chrome-stable
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - wget
    - vim
    - guake
    - PyYAML
  tags: packages
